### ISSUE TITLE
Windows 환경에서 도메인 서버 셋팅을 위해 Bind9 설치 방법과 설정파일 샘플 공유해주실 분 구합니다.

### ISSUE THREAD

**Issue by SeongSikChae** [SeongSikChae/PowerManagerDocument#1]
제 시스템에선 Bind9를 설치할 수 없는 환경이라 Document 갱신에 문제가 있네요.

**Comment by skyblue1004** [comment]
안녕하세요.
저도 공부중이라 제가 한 세팅이 맞는 방법인지는 모르겠습니다.

현재 이 세팅 방법으로 잘 사용하고 있습니다.

- BIND9 설명 유튜브 자료 -
https://youtu.be/fsrny8RADZM
https://youtu.be/AGhIPrUDryk

BIND9 디렉토리 구조
c:\bind9\bin
c:\bind9\etcs
c:\bind9\zone

에디트 프로그램은 아래 파일을 다운받아서 사용하시면 됩니다. (무료 파일 입니다.)에디트 프로그램은 아래 파일을 다운받아서 사용하시면 됩니다. (무료 파일 입니다.)
https://notepad-plus-plus.org/downloads/

*** 첨부 파일을 다운받은 후 입축을 풀면, PNG 파일로 설명이 되어 있습니다.*** 설명이 되어 있습니다.

자신의 서버IP 에 맞게 수정 하셔야 합니다
[BIND9 세팅 셈플 파일.zip](https://github.com/SeongSikChae/PowerManagerDocument/files/8242260/BIND9.zip)
.

**Comment by SeongSikChae** [comment]
https://www.isc.org/download/

9.16.26 BIND9 16.26.x64.zip Download

**Comment by SeongSikChae** [comment]
BINDInstall.exe 관리자 권한으로 실행

* 주의 Windows 11은 현재 지원하지 않음

**Comment by SeongSikChae** [comment]
![1](https://user-images.githubusercontent.com/55735227/158132262-c3e439cc-f87a-4a6d-b67e-4140007d59a5.png)

Account Password에 임의에 패스워드 입력 후 Install

**Comment by SeongSikChae** [comment]
![2](https://user-images.githubusercontent.com/55735227/158136395-9bdf87ef-f3f9-473a-93fd-910320d095ed.png)

설치

**Comment by SeongSikChae** [comment]
C:\bind9\etc 경로에 named.conf 파일 생성
```
options {
    directory "C:\bind9\zones";

    listen-on port 53 { any; };
    listen-on-v6 port 53 { none; };
    allow-query { any; };
    recursion no;
};

zone "dawonai.com" IN {
    type master;
    file "dawonai.com.zone";
    allow-transfer { none; };
    allow-update { none; };
};

zone "0.0.10.in-addr-arpa" IN {
    type master;
    file "0.0.10.zone";
    allow-transfer { none; };
    allow-update { none; };
};
```

0.0.10 은 IP 10.0.0.6에 맨 뒤를 제외한 나머지를 역순으로 적은것임. 자신의 IP에 맞게 표기

C:\bind9\bin\named-checkconf.exe 실행 에러 없으면 Success.

C:\bind9\zones 경로에 dawonai.com.zone 파일 생성

```
$TTL 1D
@   IN  SOA dawonai.com.    root (
									0   ;   serial
									1   ;   refresh
									2   ;   retry
									3   ;   expire
									4   )   ;   minimum
	IN	NS	dawonai.com.
	IN	A	10.0.0.6
dwmqtt	IN	A	10.0.0.6
dwapi	IN	A	10.0.0.6
```

C:\bind9\zones 경로에 0.0.10.zone 파일 생성

```
$TTL 1D
@	IN	SOA	dawonai.com.	root (
									0	;	serial
									1	;	refresh
									2	;	retry
									3	;	expire
									4	)	;	minimum
	IN	NS	dawonai.com.
	IN	A	10.0.0.6
6	IN	PTR	dawonai.com.
6	IN	PTR	dwmqtt.dawonai.com.
6	IN	PTR	dwapi.dawonai.com.
```

C:\bind9\bin\named-checkzone.exe dawonai.com C:\bind9\zones\dawonai.com.zone
C:\bind9\bin\named-checkzone.exe 0.0.10.in-addr-arpa C:\bind9\zones\0.0.10.zone

각 각 실행 OK 결과 나오면 Success.

윈도우 로고 + R 또는 작업관리자에서 서비스 탭에 서비스 관리자 실행

ISC BIND 서비스 찾아서 다음 사용자로 로그온에 named를 Local System으로 변경 후 서비스 시작.
[0.0.10.zone.txt](https://github.com/SeongSikChae/PowerManagerDocument/files/8243425/0.0.10.zone.txt)
[dawonai.com.zone.txt](https://github.com/SeongSikChae/PowerManagerDocument/files/8243426/dawonai.com.zone.txt)
[named.conf.txt](https://github.com/SeongSikChae/PowerManagerDocument/files/8243427/named.conf.txt)

**Comment by SeongSikChae** [comment]
명령프롬프트에 

```
nslookup dwapi.dawonai.com 10.0.0.6
```

수행 시 dwapi.dawonai.com에 결과가 해당 서버 IP가 나오면 완료.

**Comment by SeongSikChae** [comment]
Windows 에서 Bind9로 DNS 관련 정보 공유가 완료되었으므로 해당 이슈 Close.
