### ISSUE TITLE
windows10 bind9 세팅 샘플 입니다. (2022년 3월 14일자)

### ISSUE THREAD

**Issue by skyblue1004** [SeongSikChae/PowerManagerDocument#2]
<font class="papago-parent"><font class="papago-source" style="display:none;">안녕하세요.
</font>안녕하세요.</font><font class="papago-parent"><font class="papago-source" style="display:none;">저도 공부중이라 제가 한 세팅이 맞는 방법인지는 모르겠습니다.</font>저도 공부중이라 제가 한 세팅이 맞는 방법인지는 모르겠습니다.</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>
</font><font class="papago-parent"><font class="papago-source" style="display:none;">현재 이 세팅 방법으로 잘 사용하고 있습니다.</font>현재 이 세팅 방법으로 잘 사용하고 있습니다.</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>
</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>
</font><font class="papago-parent"><font class="papago-source" style="display:none;">- BIND9  설명 유튜브 자료 -
</font>- BIND9  설명 유튜브 자료 -</font><font class="papago-parent"><font class="papago-source" style="display:none;">https://youtu.be/fsrny8</font>https://youtu.be/fsrny8</font><font class="papago-parent"><font class="papago-source" style="display:none;">RADZM
</font>RADZM</font><font class="papago-parent"><font class="papago-source" style="display:none;">https://youtu.be/AGh</font>https://youtu.be/AGh</font><font class="papago-parent"><font class="papago-source" style="display:none;">IPrUDryk
</font>아이푸드리크</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>
</font><font class="papago-parent"><font class="papago-source" style="display:none;">BIND9 디렉토리 구조
</font>BIND9 디렉토리 구조</font><font class="papago-parent"><font class="papago-source" style="display:none;">c:\bind9\bin
</font>c:\cHB9\bin</font><font class="papago-parent"><font class="papago-source" style="display:none;">c:\bind9\etc
</font>c:\cHB9\etcs</font><font class="papago-parent"><font class="papago-source" style="display:none;">c:\bind9\zone
</font>c:\cHB9\zone</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>
</font><font class="papago-parent"><font class="papago-source" style="display:none;">에디트 프로그램은 아래 파일을 다운받아서 사용하시면 됩니다. (무료 파일 입니다.)</font>에디트 프로그램은 아래 파일을 다운받아서 사용하시면 됩니다. (무료 파일 입니다.)</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>
</font><font class="papago-parent"><font class="papago-source" style="display:none;">[BIND9 세팅 셈플 파일.zip](https://github.com/SeongSikCh
[BIND9 세팅 셈플 파일.zip](https://github.com/SeongSikChae/PowerManagerDocument/files/8242221/BIND9.zip)
ae/PowerManagerDocument/files/8242213/BIND9.zip)
</font>[BIND9 세팅 셈플 파일.zip](https://github.com/SeongSikChae/PowerManagerDocument/files/8242213/BIND9.zip)</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>
</font><font class="papago-parent"><font class="papago-source" style="display:none;">https://notepad-plus-plus.org/downloads/
</font>https://notepad-plus-plus.org/downloads/</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>
</font><font class="papago-parent"><font class="papago-source" style="display:none;">*** 첨부 파일을 다운받은 후 입축을 풀면, PNG 파일로 설명이 되어 있습니다.</font>*** 첨부 파일을 다운받은 후 입축을 풀면, PNG 파일로 설명이 되어 있습니다.</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>
</font><font class="papago-parent"><font class="papago-source" style="display:none;">자신의 서버IP  에 맞게 수정 하셔야 합니다.
</font>자신의 서버IP  에 맞게 수정 하셔야 합니다.</font>

**Comment by skyblue1004** [comment]
> 안녕하세요. 안녕하세요.저도 공부중이라 제가 한 세팅이 맞는 방법인지는 모르겠습니다.저도 공부중이라 제가 한 세팅이 맞는 방법인지는 모르겠습니다. 현재 이 세팅 방법으로 잘 사용하고 있습니다.현재 이 세팅 방법으로 잘 사용하고 있습니다. - BIND9 설명 유튜브 자료 - - BIND9 설명 유튜브 자료 -https://youtu.be/fsrny8https://youtu.be/fsrny8RADZM RADZMhttps://youtu.be/AGhhttps://youtu.be/AGhIPrUDryk 아이푸드리크 BIND9 디렉토리 구조 BIND9 디렉토리 구조c:\bind9\bin c:\cHB9\binc:\bind9\etc c:\cHB9\etcsc:\bind9\zone c:\cHB9\zone 에디트 프로그램은 아래 파일을 다운받아서 사용하시면 됩니다. (무료 파일 입니다.)에디트 프로그램은 아래 파일을 다운받아서 사용하시면 됩니다. (무료 파일 입니다.) [BIND9 세팅 셈플 파일.zip](https://github.com/SeongSikCh [BIND9 세팅 셈플 파일.zip](https://github.com/SeongSikChae/PowerManagerDocument/files/8242221/BIND9.zip) ae/PowerManagerDocument/files/8242213/BIND9.zip) [BIND9 세팅 셈플 파일.zip](https://github.com/SeongSikChae/PowerManagerDocument/files/8242213/BIND9.zip) https://notepad-plus-plus.org/downloads/ https://notepad-plus-plus.org/downloads/ *** 첨부 파일을 다운받은 후 입축을 풀면, PNG 파일로 설명이 되어 있습니다.*** 첨부 파일을 다운받은 후 입축을 풀면, PNG 파일로 설명이 되어 있습니다. 자신의 서버IP 에 맞게 수정 하셔야 합니다. 자신의 서버IP 에 맞게 수정 하셔야 합니다.

**Comment by SeongSikChae** [comment]
#1 관련 Issue가 있으므로 해당 Issue로 관리하기 위해 Close 조치함.
